services:
  database:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=y
        - MYSQL_DATABASE=webstore-prod
        - MYSQL_USER=owner
        - MYSQL_PASSWORD=password
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    networks:
      - anemos_network

  api:
    container_name: api
    image: ioannispanagi/anemos_api:master
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
      - DATASOURCE_JDBC_URL=jdbc:mysql://mysql-db:3306/webstore-prod
      - DATASOURCE_USERNAME=owner
      - DATASOURCE_PASSWORD=password
      - DEFAULT_UPLOAD_DIR=uploads/images/
      - DEFAULT_ACCESS_SRC=http://localhost:8081/resources/images/
    ports:
      - '8081:8080'
    networks:
      - anemos_network

  web:
    container_name: web
    image: ioannispanagi/anemos_web_customer:main
    depends_on:
      api:
        condition: service_started
    ports:
      - '3000:3000'
    networks:
      - anemos_network

volumes:
  mysql_data:

networks:
  anemos_network:
    driver: bridge
