services:
  database:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .database.env
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    networks:
      - anemos_network

  api:
    container_name: api
    image: localhost/ipanagi:anemosapilatest
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .api.env
    ports:
      - '8081:8080'
    networks:
      - anemos_network

  web:
    container_name: web
    image: localhost/ipanagi:anemosweblatest
    depends_on:
      api:
        condition: service_started
    ports:
      - '3000:3000'
    networks:
      - anemos_network

volumes:
  mysql_data:

networks:
  anemos_network:
    driver: bridge
